### ISSUE TITLE
editor_styles not compatible with WordPress 4.1

### ISSUE THREAD

**Issue by webstylr** [ProjectCleverWeb/Semantic-UI-WordPress#21]
When using Semantic-UI-WordPress with WordPress 4.1, strange things happen to the Editor/TinyMCE.
To illustrate the behavior, please see the attached screenshots.

As long as `add_editor_style('assets/styles/semantic.min.css');` is enabled, the Editor behaves in strange ways.
For example, for every mouseclick you trigger inside the Editor, a linebreak witll be inserted.
The same goes for entering content. For every character you insert, a linebreak will be added below the text. 

It looks like passing the semantic.css to tinymce causes some trouble with how tinymce constructs the editor. 
![bildschirmfoto 2014-12-28 um 13 09 08](https://cloud.githubusercontent.com/assets/413835/5563929/5f3f20ba-8e9e-11e4-8645-f5b50c3bc1d4.png)
![bildschirmfoto 2014-12-28 um 13 09 50](https://cloud.githubusercontent.com/assets/413835/5563930/5f41e034-8e9e-11e4-933a-a3edad13f6e6.png)

**Comment by ProjectCleverWeb** [comment]
Investigating this... could you please be more specific, I am not entirely sure I know what you are trying to point out.

**Comment by ProjectCleverWeb** [comment]
@webstylr I figured out what you were talking about. The editor isn't adding line breaks, it is incorrectly adjusting the height onClick. (this is what would normally prevent scroll bars from appearing when the content of the editor is larger than the default editing area.

At the moment, I am having trouble locating what exactly is causing this miscalculation, but I report back here when it is fixed.

**Comment by webstylr** [comment]
@ProjectCleverWeb sorry for being quiet for a few days, was on a short vacation ;)
While investigating this bug i found that if semtantic is loaded the html-strucure of the document is different compared to the html constructed without semtantic injected into tinymce.

HTML without semantic https://gist.github.com/webstylr/92c39a08f952984c03b9
HTML with semantic https://gist.github.com/webstylr/0afc1f6640cbc269a8cb

If there is anything i could do to help, please let me know.

**Comment by ProjectCleverWeb** [comment]
@webstylr Got this fixed, thanks for your help with finding this bug.
