### ISSUE TITLE
Lorem Ipsum dev notes

### ISSUE THREAD

**Issue by terraling** [ProjectCleverWeb/Semantic-UI-WordPress#23]
I added SUI-WP to a clean WP install for testing.

I'm seeing the Developer Notes aka the Getting Started Page but the content is all placeholder images with Lorem Ipsum text.

Is that what I should be seeing? You appear to have gone to quite a bit of trouble to organise the docs, it looks like the content is missing.

**Comment by ProjectCleverWeb** [comment]
The developer notes have note been added yet. I put in a basic layout for them, and added some section headers for things I plan on adding, but there are no actual notes. Sorry.

However, if you have any questions, go ahead and ask them here and I will get back to you.
