### ISSUE TITLE
Menus don't display

### ISSUE THREAD

**Issue by terraling** [ProjectCleverWeb/Semantic-UI-WordPress#24]
Testing SUI-WP on a clean WP install.

Have created a new menu and set it to display in both locations – Main menu & Footer menu – but it is not showing up in either.

**Comment by ProjectCleverWeb** [comment]
hmm, I can only reproduce this by adding menus that don't have any items.

Are you sure you saved your menu after you added the menu items?

**Comment by terraling** [comment]
I've gone ahead and started over with a clean install again and this time it is showing the main menu, something must have slipped twixt download and install.

But... in menu locations there are Main Menu and Footer Menu. If I assign my menu to Footer Menu nothing shows up in the footer, although it sounds like it ought to. (You can see it at a temporary live site here: yoterraling.dollarwp.com)

**Comment by ProjectCleverWeb** [comment]
This is confirmed, the footer menu was never called. (although it should have been)

You can fix this in your current version with:

```php
$menu = new \semantic\menu_walker;
$menu->display('main-menu');
```

This will be fixed in `develop` soon
