### ISSUE TITLE
Uploading image issue 

### ISSUE THREAD

**Issue by Ralphkay** [ProjectCleverWeb/Semantic-UI-WordPress#38]
Please, I made a child theme out of semantic-UI-WordPress theme, however when I try uploading images or any media, it fails to upload. Please Can I get some help with this issue. Thank you.

**Comment by ProjectCleverWeb** [comment]
To help rule out errors, can you please make sure all plugins are disabled.

Additionally, when it fails, what does it say? Does the console produce any errors? (Console can be opened with <kbd>F12</kbd> in Chrome)

**Comment by krishaamer** [comment]
+1

The uploads fail on a clean install with 0 plugins activated. Both on localhost and remote server. The WP errors are not really descriptive. JS console doesn't show any errors.

![screen shot 2016-04-05 at 01 59 30](https://cloud.githubusercontent.com/assets/54409/14266629/1fb8bdc4-fad2-11e5-9525-5d9bda08c4c8.png)

**Comment by ProjectCleverWeb** [comment]
An update will be push out soon, but here is a fix for you guys for now:

In `include/class/semantic/shutdown.php` at about line 88, change this:

```
public function _run_shutdown() {
    global $debug;
    foreach ($this->jobs as $id => $job) {
        $debug->runtime_checkpoint(sprintf('[Theme] Shutdown - Running "%s"...', $id));
        call_user_func_array($job['callback'], $job['args']);
    }
    $this->jobs = array();
}
```

To This:

```
public function _run_shutdown() {
    if (in_array($GLOBALS['pagenow'], array('admin-ajax.php', 'async-upload.php'))) {
        return;
    }
    global $debug;
    foreach ($this->jobs as $id => $job) {
        $debug->runtime_checkpoint(sprintf('[Theme] Shutdown - Running "%s"...', $id));
        call_user_func_array($job['callback'], $job['args']);
    }
    $this->jobs = array();
}
```
